// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Capsule struct {
	ID             int32              `json:"id"`
	OwnerID        string             `json:"owner_id"`
	RecipientEmail string             `json:"recipient_email"`
	Message        string             `json:"message"`
	MediaUrl       string             `json:"media_url"`
	UnlockAt       time.Time          `json:"unlock_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
