// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createCapsule = `-- name: CreateCapsule :one
INSERT INTO capsules (
  owner_id,
  recipient_email,
  message,
  media_url,
  unlock_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, owner_id, recipient_email, message, media_url, unlock_at, delivered_at, created_at, updated_at, deleted_at
`

type CreateCapsuleParams struct {
	OwnerID        string    `json:"owner_id"`
	RecipientEmail string    `json:"recipient_email"`
	Message        string    `json:"message"`
	MediaUrl       string    `json:"media_url"`
	UnlockAt       time.Time `json:"unlock_at"`
}

func (q *Queries) CreateCapsule(ctx context.Context, arg CreateCapsuleParams) (Capsule, error) {
	row := q.db.QueryRow(ctx, createCapsule,
		arg.OwnerID,
		arg.RecipientEmail,
		arg.Message,
		arg.MediaUrl,
		arg.UnlockAt,
	)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RecipientEmail,
		&i.Message,
		&i.MediaUrl,
		&i.UnlockAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash
) VALUES (
  $1, $2
)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapsule = `-- name: GetCapsule :one
SELECT id, owner_id, recipient_email, message, media_url, unlock_at, delivered_at, created_at, updated_at, deleted_at FROM capsules
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCapsule(ctx context.Context, id int32) (Capsule, error) {
	row := q.db.QueryRow(ctx, getCapsule, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RecipientEmail,
		&i.Message,
		&i.MediaUrl,
		&i.UnlockAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapsules = `-- name: ListCapsules :many
SELECT id, owner_id, recipient_email, message, media_url, unlock_at, delivered_at, created_at, updated_at, deleted_at FROM capsules
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCapsules(ctx context.Context, ownerID string) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsules, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RecipientEmail,
			&i.Message,
			&i.MediaUrl,
			&i.UnlockAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
